// <auto-generated />
using System;
using API_XML_XSLT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_XML_XSLT.Migrations
{
    [DbContext(typeof(TootajaDbContext))]
    [Migration("20241118192042_DBCreating")]
    partial class DBCreating
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_XML_XSLT.Models.Igapaeva_andmed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Kuupaev")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("Too_algus")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("Too_lypp")
                        .HasColumnType("time");

                    b.Property<int>("TootajaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TootajaId");

                    b.ToTable("IgapaevaAndmed");
                });

            modelBuilder.Entity("API_XML_XSLT.Models.Tootaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Is_admin")
                        .HasColumnType("bit");

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Perenimi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Salasyna")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefoni_number")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Tootajad");
                });

            modelBuilder.Entity("API_XML_XSLT.Models.Igapaeva_andmed", b =>
                {
                    b.HasOne("API_XML_XSLT.Models.Tootaja", "Tootaja")
                        .WithMany("Igapaeva_Andmed")
                        .HasForeignKey("TootajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tootaja");
                });

            modelBuilder.Entity("API_XML_XSLT.Models.Tootaja", b =>
                {
                    b.Navigation("Igapaeva_Andmed");
                });
#pragma warning restore 612, 618
        }
    }
}
